site_name: FullStaQD Architecture Documentation
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/moon
        name: Switch to system preference
  logo: images/fullstaqd-logo-square.png
  favicon: images/fullstaqd-logo-square.png
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
markdown_extensions: 
  - attr_list
  - md_in_html # for using markdown in <figure>s

  # for adminitions, source:
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - toc:
      toc_depth: 4
repo_url: https://github.com/fullstaqd/architecture
repo_name: FullStaQD/architecture
edit_uri: edit/main/docs/
site_url: https://fullstaqd.github.io/architecture/

extra: 
  version:
    provider: mike

nav:
  - index.md
  - Reference Architecture:
    - reference-architecture/index.md
    - reference-architecture/introduction-and-goals.md
    - reference-architecture/architecture-constraints.md
    - reference-architecture/context-and-scope.md
    - reference-architecture/solution-strategy.md
    - reference-architecture/building-block-view.md
    - reference-architecture/runtime-view.md
    - reference-architecture/deployment-view.md
    - reference-architecture/cross-cutting-concepts.md
    - reference-architecture/architecture-decisions.md
    - reference-architecture/quality-requirements.md
    - reference-architecture/technical-risks.md
    - reference-architecture/glossary.md
  - Scenario-Based Analysis:
    - scenario-based-analysis/index.md
    - scenario-based-analysis/quantum-simulation.md
    - scenario-based-analysis/cloud-optimisation.md
    - scenario-based-analysis/embedded.md
    - scenario-based-analysis/quantum-machine-learning.md
  - Reference Implementation:
    - reference-implementation/index.md
