site_name: FullStaQD Reference Architecture
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
  custom_dir: overrides
markdown_extensions: 
  - attr_list
  - md_in_html # for using markdown in <figure>s

  # for adminitions, source:
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - toc:
      toc_depth: 4
repo_url: https://github.com/fullstaqd/architecture
repo_name: FullStaQD/architecture
edit_uri: edit/main/docs/
site_url: https://fullstaqd.github.io/architecture/

extra: 
  version:
    provider: mike
