[project]
name = "architecture"
version = "0.0.0"
description = "Reference architecture documentation for FullStaQD"
readme = "README.md"
authors = [
    {name = "Max Schweikart", email = "schweikart@kit.edu"},
    {name = "Rinor Kelmendi"},
    {name = "Ina Schaefer"}
]
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "mike",
    "zensical>=0.0.51",
]

[tool.uv.sources]
mike = { git = "https://github.com/squidfunk/mike.git" }
